# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff9771b428a6641b849851b05b6eb4f936fc7ea618d31fe54573bf8327248cb0cc2bea6d991a5552b96301c2b4d7fb592bc1be2b55db7f72d73afbf03b1cb44

test:
  secret_key_base: 907638786f6ce7d1c1c5626adf4e82633e47fa10f7d06d61fb6cb844c0132869aefd95d2e08d624ebc05d44e5989167d307843a1ec78c65e60b3f3e5cf1dc2fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
